export interface IndustryProfile {
  slug: string;
  name: string;
  type: "service" | "retail" | "healthcare" | "professional" | "education" | "food" | "creative" | "home-service" | "wellness" | "events";
  painPoints: string[];
  workflows: string[];
  customerType: string;
  businessSize: string;
  techLevel: "low" | "medium" | "high";
  contentNeeds: string[];
  keyTerms: string[];
}

export const INDUSTRY_PROFILES: IndustryProfile[] = [
  {
    slug: "landscaping",
    name: "Landscaping",
    type: "home-service",
    painPoints: ["seasonal demand fluctuations", "managing crews across multiple job sites", "providing accurate estimates from photos", "standing out in a crowded local market"],
    workflows: ["quoting and estimating jobs", "scheduling crews", "sending before/after photos to clients", "managing seasonal marketing pushes"],
    customerType: "homeowners and commercial property managers",
    businessSize: "small crews of 3-15",
    techLevel: "low",
    contentNeeds: ["seasonal promotions", "before/after showcase posts", "local SEO content", "customer follow-up emails"],
    keyTerms: ["hardscaping", "lawn care", "seasonal cleanup", "landscape design", "irrigation"],
  },
  {
    slug: "food-trucks",
    name: "Food Trucks",
    type: "food",
    painPoints: ["building a following to drive foot traffic", "communicating daily locations and menus", "standing out at events and festivals", "managing social media on-the-go"],
    workflows: ["posting daily location updates", "creating menu specials content", "engaging with followers for event bookings", "running promotions for catering gigs"],
    customerType: "local foodies and event organizers",
    businessSize: "1-5 person operations",
    techLevel: "medium",
    contentNeeds: ["daily location posts", "menu updates", "event announcements", "customer engagement"],
    keyTerms: ["food truck rally", "pop-up", "catering", "street food", "commissary kitchen"],
  },
  {
    slug: "dental-practices",
    name: "Dental Practices",
    type: "healthcare",
    painPoints: ["patient communication and appointment reminders", "explaining complex procedures to anxious patients", "HIPAA-compliant communications", "competing with corporate dental chains"],
    workflows: ["sending appointment reminders", "drafting treatment plan explanations", "creating patient education content", "managing insurance communications"],
    customerType: "patients of all ages",
    businessSize: "2-20 staff including hygienists and front desk",
    techLevel: "medium",
    contentNeeds: ["patient education materials", "procedure explanations", "appointment confirmations", "insurance letters"],
    keyTerms: ["hygiene recall", "treatment plan", "insurance verification", "patient recall", "HIPAA"],
  },
  {
    slug: "real-estate-agents",
    name: "Real Estate Agents",
    type: "professional",
    painPoints: ["creating compelling property listings quickly", "nurturing leads across long sales cycles", "producing market analysis reports", "standing out on social media"],
    workflows: ["writing property descriptions", "creating market update newsletters", "responding to buyer/seller inquiries", "generating social media content for listings"],
    customerType: "home buyers and sellers",
    businessSize: "solo agents or small teams of 2-10",
    techLevel: "medium",
    contentNeeds: ["property descriptions", "market updates", "email newsletters", "social media posts", "buyer/seller guides"],
    keyTerms: ["MLS", "open house", "comparable sales", "escrow", "closing", "pre-approval"],
  },
  {
    slug: "plumbing",
    name: "Plumbing",
    type: "home-service",
    painPoints: ["emergency call management", "explaining repair costs to skeptical homeowners", "generating leads during slow seasons", "competing with low-ball competitors"],
    workflows: ["dispatching techs to emergency calls", "creating repair estimates", "following up with customers for maintenance", "generating reviews and referrals"],
    customerType: "homeowners and property managers",
    businessSize: "1-10 technicians plus office staff",
    techLevel: "low",
    contentNeeds: ["emergency service content", "seasonal maintenance tips", "estimate follow-ups", "review request messages"],
    keyTerms: ["water heater", "drain cleaning", "sewer line", "fixture installation", "emergency plumbing"],
  },
  {
    slug: "hvac",
    name: "HVAC",
    type: "home-service",
    painPoints: ["seasonal demand spikes in summer and winter", "educating customers on system efficiency", "managing maintenance contract renewals", "competing on price vs quality"],
    workflows: ["scheduling seasonal tune-ups", "creating maintenance agreement proposals", "educating customers on energy savings", "managing warranty communications"],
    customerType: "homeowners and commercial building managers",
    businessSize: "5-25 technicians with office support",
    techLevel: "low",
    contentNeeds: ["seasonal service reminders", "energy savings tips", "maintenance agreement details", "equipment upgrade promotions"],
    keyTerms: ["SEER rating", "heat pump", "ductwork", "thermostat", "preventive maintenance", "refrigerant"],
  },
  {
    slug: "auto-repair",
    name: "Auto Repair",
    type: "service",
    painPoints: ["building trust with customers unfamiliar with car repairs", "explaining complex repairs in simple terms", "managing parts ordering and inventory", "competing with dealership service departments"],
    workflows: ["writing repair estimates", "explaining diagnostic findings", "sending service reminders", "managing customer approval for repairs"],
    customerType: "vehicle owners",
    businessSize: "2-15 mechanics plus front desk",
    techLevel: "low",
    contentNeeds: ["repair explanations", "maintenance reminders", "seasonal car care tips", "service promotions"],
    keyTerms: ["diagnostic", "brake service", "oil change", "transmission", "check engine light"],
  },
  {
    slug: "salons",
    name: "Salons",
    type: "wellness",
    painPoints: ["filling last-minute cancellation slots", "maintaining a strong Instagram presence", "managing stylist schedules", "retaining clients against competition"],
    workflows: ["posting transformation photos on social media", "sending appointment reminders", "promoting seasonal styles and specials", "managing client loyalty programs"],
    customerType: "individuals seeking hair and beauty services",
    businessSize: "2-15 stylists plus front desk",
    techLevel: "medium",
    contentNeeds: ["social media transformation posts", "booking confirmations", "seasonal trend content", "loyalty program updates"],
    keyTerms: ["balayage", "color correction", "blowout", "stylist", "booking", "walk-in"],
  },
  {
    slug: "photography",
    name: "Photography",
    type: "creative",
    painPoints: ["showcasing portfolio work effectively online", "managing client communications across bookings", "writing proposals that win high-value gigs", "standing out in an oversaturated market"],
    workflows: ["writing client proposals", "sending booking confirmations and shot lists", "creating blog posts showcasing sessions", "managing social media portfolio"],
    customerType: "couples, families, and businesses needing professional photos",
    businessSize: "solo or 2-5 person studios",
    techLevel: "medium",
    contentNeeds: ["client proposals", "session blog posts", "portfolio descriptions", "booking confirmations", "social media captions"],
    keyTerms: ["golden hour", "retouching", "shot list", "deliverables", "lightroom", "gallery"],
  },
  {
    slug: "personal-trainers",
    name: "Personal Trainers",
    type: "wellness",
    painPoints: ["attracting and retaining clients in a competitive fitness market", "creating personalized workout and nutrition plans", "managing scheduling across multiple clients", "building an online presence to grow beyond in-person training"],
    workflows: ["creating workout programs", "tracking client progress", "sending motivational check-ins", "marketing services on social media"],
    customerType: "fitness-seeking individuals",
    businessSize: "solo practitioners or small teams of 2-5",
    techLevel: "medium",
    contentNeeds: ["workout plans", "nutrition tips", "progress updates", "motivational content", "social media fitness posts"],
    keyTerms: ["reps", "sets", "macros", "HIIT", "progressive overload", "body composition"],
  },
  {
    slug: "yoga-studios",
    name: "Yoga Studios",
    type: "wellness",
    painPoints: ["competing with online yoga platforms and free YouTube content", "communicating class schedules and changes", "building community beyond the mat", "managing instructor schedules"],
    workflows: ["updating class schedules", "sending workshop announcements", "creating wellness content for email lists", "managing membership communications"],
    customerType: "wellness-focused individuals",
    businessSize: "1-5 instructors plus admin",
    techLevel: "medium",
    contentNeeds: ["class schedule updates", "workshop promotions", "wellness blog posts", "community newsletters"],
    keyTerms: ["vinyasa", "restorative", "workshop", "class pass", "meditation", "mindfulness"],
  },
  {
    slug: "pet-grooming",
    name: "Pet Grooming",
    type: "service",
    painPoints: ["managing a packed appointment schedule", "communicating with anxious pet owners", "showcasing grooming results to attract new clients", "handling no-shows and late cancellations"],
    workflows: ["booking and confirming appointments", "sending grooming completion notifications", "posting before/after photos on social media", "managing client pet preferences and notes"],
    customerType: "pet owners",
    businessSize: "1-6 groomers",
    techLevel: "low",
    contentNeeds: ["appointment reminders", "before/after showcase posts", "seasonal grooming tips", "pet care advice content"],
    keyTerms: ["breed-specific cut", "deshedding", "nail trimming", "dematting", "puppy cut"],
  },
  {
    slug: "veterinary-clinics",
    name: "Veterinary Clinics",
    type: "healthcare",
    painPoints: ["communicating complex diagnoses to worried pet owners", "managing vaccination and wellness reminders", "handling emergency after-hours inquiries", "maintaining HIPAA-like privacy standards for client records"],
    workflows: ["sending vaccination reminders", "explaining treatment options to pet owners", "managing prescription refill communications", "creating pet health education content"],
    customerType: "pet owners",
    businessSize: "3-20 staff including vets, techs, and front desk",
    techLevel: "medium",
    contentNeeds: ["vaccination reminders", "treatment explanations", "pet health education", "seasonal pet care tips"],
    keyTerms: ["wellness exam", "vaccination schedule", "spay/neuter", "diagnostic imaging", "prescription diet"],
  },
  {
    slug: "cleaning-services",
    name: "Cleaning Services",
    type: "home-service",
    painPoints: ["differentiating from dozens of local competitors", "managing recurring service schedules", "handling customer complaints professionally", "scaling from residential to commercial clients"],
    workflows: ["creating service quotes", "sending appointment reminders", "following up for reviews", "marketing seasonal deep-cleaning specials"],
    customerType: "homeowners and commercial offices",
    businessSize: "1-20 cleaning staff",
    techLevel: "low",
    contentNeeds: ["service descriptions", "cleaning tips content", "quote follow-ups", "review requests"],
    keyTerms: ["deep clean", "move-in/move-out", "recurring service", "green cleaning", "commercial cleaning"],
  },
  {
    slug: "roofing",
    name: "Roofing",
    type: "home-service",
    painPoints: ["selling high-ticket jobs to cautious homeowners", "providing detailed estimates with material breakdowns", "managing storm damage surge demand", "building trust and credibility"],
    workflows: ["creating detailed repair and replacement estimates", "following up with insurance adjusters", "producing storm damage assessment reports", "generating content for lead generation"],
    customerType: "homeowners and property managers",
    businessSize: "5-30 crew members plus office staff",
    techLevel: "low",
    contentNeeds: ["estimate proposals", "storm damage guides", "material comparison content", "insurance claim guidance"],
    keyTerms: ["shingle", "flashing", "roof deck", "ice dam", "storm damage", "insurance claim"],
  },
  {
    slug: "electricians",
    name: "Electricians",
    type: "home-service",
    painPoints: ["educating customers on electrical safety and code compliance", "generating leads for non-emergency work", "explaining cost differences vs handyman services", "managing service call scheduling"],
    workflows: ["creating job estimates", "sending safety inspection reports", "following up on completed work", "marketing energy efficiency upgrades"],
    customerType: "homeowners, contractors, and commercial property managers",
    businessSize: "1-15 electricians plus admin",
    techLevel: "low",
    contentNeeds: ["safety tip content", "energy savings guides", "estimate follow-ups", "code compliance explanations"],
    keyTerms: ["panel upgrade", "circuit breaker", "wiring", "code compliance", "EV charger installation"],
  },
  {
    slug: "moving-companies",
    name: "Moving Companies",
    type: "service",
    painPoints: ["competing on price while maintaining quality", "managing inventory lists and damage claims", "handling peak season demand", "building trust with customers entrusting their possessions"],
    workflows: ["creating move estimates based on inventory", "sending pre-move checklists", "coordinating crew schedules", "following up for reviews after moves"],
    customerType: "families and businesses relocating",
    businessSize: "5-30 movers plus dispatch",
    techLevel: "low",
    contentNeeds: ["move estimates", "packing tip guides", "pre-move checklists", "customer follow-ups"],
    keyTerms: ["cubic feet", "packing materials", "long-distance move", "storage unit", "binding estimate"],
  },
  {
    slug: "tutoring",
    name: "Tutoring",
    type: "education",
    painPoints: ["communicating student progress to parents effectively", "creating customized lesson plans", "competing with online tutoring platforms", "scheduling across multiple students and subjects"],
    workflows: ["preparing lesson plans", "writing student progress reports", "communicating with parents", "marketing tutoring services locally"],
    customerType: "students and parents",
    businessSize: "solo or 2-10 tutors",
    techLevel: "medium",
    contentNeeds: ["progress reports", "lesson summaries", "study tips content", "parent communication", "marketing materials"],
    keyTerms: ["SAT prep", "learning style", "grade improvement", "one-on-one", "test prep"],
  },
  {
    slug: "daycares",
    name: "Daycares",
    type: "education",
    painPoints: ["communicating daily activities and child wellbeing to parents", "meeting state licensing and safety requirements", "managing waitlists and enrollment", "creating trust with anxious parents"],
    workflows: ["sending daily activity reports", "managing enrollment communications", "creating parent newsletters", "documenting compliance activities"],
    customerType: "parents of young children",
    businessSize: "5-25 staff including caregivers and admin",
    techLevel: "low",
    contentNeeds: ["daily activity updates", "parent newsletters", "enrollment communications", "safety procedure documentation"],
    keyTerms: ["ratio requirements", "licensing", "curriculum", "drop-off/pick-up", "incident report"],
  },
  {
    slug: "restaurants",
    name: "Restaurants",
    type: "food",
    painPoints: ["managing online reputation across review platforms", "keeping menus and specials updated across channels", "filling seats during slow periods", "standing out in a saturated dining market"],
    workflows: ["updating daily specials on social media", "responding to online reviews", "creating seasonal menu descriptions", "managing reservation confirmations"],
    customerType: "diners and food enthusiasts",
    businessSize: "10-50 staff including kitchen and front-of-house",
    techLevel: "medium",
    contentNeeds: ["menu descriptions", "daily specials posts", "review responses", "event promotions"],
    keyTerms: ["farm-to-table", "prix fixe", "happy hour", "reservation", "online ordering"],
  },
  {
    slug: "coffee-shops",
    name: "Coffee Shops",
    type: "food",
    painPoints: ["building a loyal local following", "differentiating from chain coffee shops", "promoting seasonal drinks and events", "managing social media consistently"],
    workflows: ["posting daily coffee features", "promoting events like open mic nights", "engaging with the local community online", "creating loyalty program communications"],
    customerType: "local coffee enthusiasts and remote workers",
    businessSize: "3-15 baristas and staff",
    techLevel: "medium",
    contentNeeds: ["daily drink features", "event promotions", "community engagement posts", "loyalty program updates"],
    keyTerms: ["single-origin", "pour-over", "latte art", "cold brew", "roast profile"],
  },
  {
    slug: "bakeries",
    name: "Bakeries",
    type: "food",
    painPoints: ["showcasing baked goods visually to drive orders", "managing custom cake and catering orders", "handling seasonal demand spikes for holidays", "writing enticing product descriptions"],
    workflows: ["taking and confirming custom orders", "posting product photos on social media", "creating seasonal menus and promotions", "managing wholesale and retail communications"],
    customerType: "individuals and event planners ordering baked goods",
    businessSize: "3-15 bakers and counter staff",
    techLevel: "low",
    contentNeeds: ["product descriptions", "order confirmations", "seasonal promotion posts", "custom order consultations"],
    keyTerms: ["artisan bread", "fondant", "buttercream", "sourdough", "custom cake", "wedding cake"],
  },
  {
    slug: "catering",
    name: "Catering",
    type: "food",
    painPoints: ["creating detailed proposals that win corporate and event contracts", "managing complex dietary requirements", "coordinating logistics across multiple events", "building a reputation beyond word-of-mouth"],
    workflows: ["writing event proposals", "managing menu customizations", "coordinating with event planners", "following up on inquiries"],
    customerType: "corporate event planners, wedding couples, and party hosts",
    businessSize: "5-30 kitchen and serving staff",
    techLevel: "medium",
    contentNeeds: ["event proposals", "menu descriptions", "dietary accommodation details", "follow-up communications"],
    keyTerms: ["per-head pricing", "buffet", "plated service", "dietary restrictions", "tasting", "BEO"],
  },
  {
    slug: "florists",
    name: "Florists",
    type: "retail",
    painPoints: ["showcasing arrangements in a way that drives online orders", "managing wedding and event consultations efficiently", "competing with online flower delivery services", "handling holiday rush order volume"],
    workflows: ["creating arrangement descriptions for website", "managing wedding consultations", "posting seasonal arrangements on social media", "sending order and delivery confirmations"],
    customerType: "individuals, couples planning weddings, and corporate clients",
    businessSize: "2-10 floral designers and shop staff",
    techLevel: "low",
    contentNeeds: ["arrangement descriptions", "wedding consultation follow-ups", "seasonal content", "delivery confirmations"],
    keyTerms: ["centerpiece", "bouquet", "corsage", "seasonal blooms", "floral foam", "sympathy arrangement"],
  },
  {
    slug: "wedding-planners",
    name: "Wedding Planners",
    type: "events",
    painPoints: ["managing dozens of vendor relationships simultaneously", "creating detailed proposals that justify premium pricing", "handling anxious clients with high expectations", "keeping organized across multiple concurrent weddings"],
    workflows: ["writing proposals and timelines", "coordinating vendor communications", "sending client updates", "creating day-of schedules"],
    customerType: "engaged couples planning their wedding",
    businessSize: "solo or small teams of 2-5 planners",
    techLevel: "medium",
    contentNeeds: ["proposals", "vendor correspondence", "client update emails", "timeline documents", "social media inspiration posts"],
    keyTerms: ["venue", "vendor coordination", "day-of timeline", "rehearsal", "reception", "decor"],
  },
  {
    slug: "fitness-studios",
    name: "Fitness Studios",
    type: "wellness",
    painPoints: ["retaining members against gym and app competition", "filling class spots during off-peak hours", "creating engaging content to build community", "managing instructor schedules and substitutions"],
    workflows: ["sending class schedule updates", "promoting challenges and events", "creating workout-related content", "managing membership communications"],
    customerType: "fitness enthusiasts and people starting their fitness journey",
    businessSize: "3-15 instructors plus admin",
    techLevel: "medium",
    contentNeeds: ["class promotions", "challenge announcements", "fitness tips", "member success stories"],
    keyTerms: ["HIIT class", "spin", "barre", "membership", "class pack", "studio challenge"],
  },
  {
    slug: "martial-arts-schools",
    name: "Martial Arts Schools",
    type: "education",
    painPoints: ["attracting new students beyond word-of-mouth", "retaining students through belt progressions", "communicating with parents of young students", "differentiating from other local schools"],
    workflows: ["promoting trial classes", "sending belt test notifications", "creating curriculum-related content", "managing event and tournament communications"],
    customerType: "children, teens, and adults interested in martial arts",
    businessSize: "1-5 instructors plus front desk",
    techLevel: "low",
    contentNeeds: ["trial class promotions", "belt progression updates", "tournament announcements", "self-defense tips content"],
    keyTerms: ["belt rank", "sparring", "kata", "dojo", "gi", "self-defense"],
  },
  {
    slug: "chiropractic",
    name: "Chiropractic",
    type: "healthcare",
    painPoints: ["educating patients on the value of ongoing chiropractic care", "managing patient reactivation campaigns", "handling insurance documentation", "competing with physical therapy and massage offerings"],
    workflows: ["sending appointment reminders", "creating patient education content", "managing insurance letters", "running reactivation campaigns for lapsed patients"],
    customerType: "patients with back pain, sports injuries, and wellness goals",
    businessSize: "1-5 chiropractors plus support staff",
    techLevel: "medium",
    contentNeeds: ["patient education articles", "appointment reminders", "insurance documentation", "reactivation emails"],
    keyTerms: ["adjustment", "subluxation", "spinal alignment", "wellness plan", "X-ray", "maintenance care"],
  },
  {
    slug: "optometry",
    name: "Optometry",
    type: "healthcare",
    painPoints: ["communicating complex vision prescriptions to patients", "managing annual exam reminders at scale", "competing with online eyewear retailers", "explaining insurance coverage and out-of-pocket costs"],
    workflows: ["sending annual exam reminders", "explaining vision prescription changes", "promoting eyewear collections", "managing insurance pre-authorizations"],
    customerType: "patients needing vision care",
    businessSize: "2-10 staff including optometrists and opticians",
    techLevel: "medium",
    contentNeeds: ["exam reminders", "eye health education", "eyewear promotions", "insurance coverage explanations"],
    keyTerms: ["comprehensive exam", "contact lens fitting", "progressive lenses", "vision insurance", "retinal imaging"],
  },
  {
    slug: "therapy-practices",
    name: "Therapy Practices",
    type: "healthcare",
    painPoints: ["maintaining strict patient confidentiality in all communications", "managing waitlists and new patient intake", "creating content that reduces mental health stigma", "handling insurance credentialing and billing communication"],
    workflows: ["managing new patient intake paperwork", "sending appointment reminders", "creating psychoeducation content", "handling insurance billing communications"],
    customerType: "individuals seeking mental health support",
    businessSize: "solo therapists or group practices of 2-10",
    techLevel: "medium",
    contentNeeds: ["intake forms", "appointment reminders", "psychoeducation content", "insurance communications"],
    keyTerms: ["intake session", "treatment plan", "HIPAA", "sliding scale", "telehealth", "evidence-based"],
  },
  {
    slug: "law-firms",
    name: "Law Firms",
    type: "professional",
    painPoints: ["drafting and reviewing large volumes of legal documents", "managing client communications with precision", "tracking billable hours and producing client reports", "marketing legal services without violating ethics rules"],
    workflows: ["drafting legal documents and contracts", "writing client advisories", "preparing case summaries", "creating thought leadership content"],
    customerType: "individuals and businesses needing legal services",
    businessSize: "solo practitioners to firms of 5-50",
    techLevel: "high",
    contentNeeds: ["legal document drafts", "client advisories", "case summaries", "blog articles on legal topics"],
    keyTerms: ["retainer", "discovery", "brief", "deposition", "billable hours", "client intake"],
  },
  {
    slug: "accounting-firms",
    name: "Accounting Firms",
    type: "professional",
    painPoints: ["managing tax season workload surges", "communicating complex financial information to clients", "staying current with changing tax regulations", "competing with DIY accounting software"],
    workflows: ["preparing client tax documents", "writing financial advisory letters", "creating tax planning recommendations", "managing client document requests"],
    customerType: "individuals and businesses needing tax and accounting services",
    businessSize: "solo CPAs to firms of 5-30",
    techLevel: "high",
    contentNeeds: ["tax planning letters", "financial summaries", "regulatory update communications", "client advisory content"],
    keyTerms: ["1099", "W-2", "quarterly estimates", "audit", "bookkeeping", "CPA"],
  },
  {
    slug: "insurance-agencies",
    name: "Insurance Agencies",
    type: "professional",
    painPoints: ["explaining complex policies in plain language", "managing policy renewal communications at scale", "generating leads in a trust-dependent industry", "handling claims assistance communication"],
    workflows: ["writing policy explanations", "sending renewal reminders", "creating educational content about coverage", "managing claims communications"],
    customerType: "individuals and businesses needing insurance coverage",
    businessSize: "solo agents to agencies of 5-20",
    techLevel: "medium",
    contentNeeds: ["policy explanations", "renewal reminders", "coverage guides", "claims assistance communications"],
    keyTerms: ["premium", "deductible", "coverage limits", "policy term", "endorsement", "claims"],
  },
  {
    slug: "property-management",
    name: "Property Management",
    type: "professional",
    painPoints: ["communicating with tenants efficiently at scale", "managing maintenance requests and vendor coordination", "producing owner reports and financial statements", "handling lease renewals and vacancy marketing"],
    workflows: ["sending tenant communications", "coordinating maintenance requests", "producing monthly owner reports", "creating vacancy listings"],
    customerType: "property owners and tenants",
    businessSize: "1-10 property managers handling 50-500 units",
    techLevel: "medium",
    contentNeeds: ["tenant notices", "maintenance updates", "owner reports", "vacancy listing descriptions"],
    keyTerms: ["lease", "maintenance request", "turnover", "vacancy rate", "rent collection", "HOA"],
  },
  {
    slug: "construction",
    name: "Construction",
    type: "home-service",
    painPoints: ["creating detailed project proposals that win bids", "managing complex project timelines and communications", "documenting progress for clients and inspectors", "handling change order negotiations"],
    workflows: ["writing project proposals and bids", "sending progress updates to clients", "managing subcontractor communications", "creating change order documentation"],
    customerType: "homeowners, developers, and commercial clients",
    businessSize: "5-50 crew members plus project managers",
    techLevel: "medium",
    contentNeeds: ["project proposals", "progress reports", "change order documentation", "safety documentation"],
    keyTerms: ["bid", "general contractor", "subcontractor", "change order", "punch list", "permit"],
  },
  {
    slug: "interior-design",
    name: "Interior Design",
    type: "creative",
    painPoints: ["creating compelling design proposals that justify fees", "communicating design concepts to non-visual clients", "managing multiple projects with different timelines", "marketing design services with a personal brand"],
    workflows: ["writing design proposals", "presenting mood boards and concepts", "managing vendor and contractor communications", "creating portfolio content"],
    customerType: "homeowners, businesses, and developers",
    businessSize: "solo designers or small firms of 2-8",
    techLevel: "medium",
    contentNeeds: ["design proposals", "concept descriptions", "project update emails", "portfolio descriptions", "blog content"],
    keyTerms: ["mood board", "space planning", "specification", "FF&E", "rendering", "color palette"],
  },
  {
    slug: "tattoo-shops",
    name: "Tattoo Shops",
    type: "creative",
    painPoints: ["managing consultation requests and design approvals", "showcasing artist portfolios effectively online", "communicating aftercare instructions clearly", "building a brand that attracts the right clientele"],
    workflows: ["handling consultation inquiries", "managing design approval communications", "sending aftercare instructions", "posting portfolio updates on social media"],
    customerType: "individuals seeking custom tattoo art",
    businessSize: "2-8 artists plus front desk",
    techLevel: "medium",
    contentNeeds: ["consultation responses", "aftercare guides", "portfolio descriptions", "artist bio content"],
    keyTerms: ["flash sheet", "custom design", "sleeve", "aftercare", "touch-up", "walk-in"],
  },
  {
    slug: "car-washes",
    name: "Car Washes",
    type: "service",
    painPoints: ["converting one-time customers to monthly membership plans", "managing weather-dependent demand", "differentiating from competitors on the same strip", "promoting premium services beyond basic washes"],
    workflows: ["promoting membership plans", "sending weather-triggered promotions", "managing customer loyalty communications", "upselling premium detailing services"],
    customerType: "vehicle owners",
    businessSize: "5-20 staff",
    techLevel: "low",
    contentNeeds: ["membership promotions", "seasonal offers", "detailing service descriptions", "loyalty program updates"],
    keyTerms: ["detail", "ceramic coating", "express wash", "monthly membership", "hand wash"],
  },
  {
    slug: "pest-control",
    name: "Pest Control",
    type: "home-service",
    painPoints: ["educating homeowners on prevention vs reactive treatments", "managing seasonal pest cycles with timely marketing", "handling anxious customers dealing with infestations", "explaining treatment safety and chemicals used"],
    workflows: ["creating pest identification and treatment guides", "sending seasonal service reminders", "following up after treatments", "managing recurring service schedules"],
    customerType: "homeowners and commercial property managers",
    businessSize: "3-15 technicians plus office staff",
    techLevel: "low",
    contentNeeds: ["pest identification guides", "service reminders", "treatment follow-ups", "seasonal pest alerts"],
    keyTerms: ["termite inspection", "integrated pest management", "quarterly treatment", "rodent exclusion", "bed bug"],
  },
  {
    slug: "tree-service",
    name: "Tree Service",
    type: "home-service",
    painPoints: ["providing accurate estimates for large tree removal jobs", "communicating safety risks to customers", "generating work during off-season months", "building credibility for high-value jobs"],
    workflows: ["creating tree removal and trimming estimates", "documenting hazardous conditions", "marketing storm damage services", "following up for annual maintenance"],
    customerType: "homeowners and commercial property managers",
    businessSize: "3-15 crew members plus office",
    techLevel: "low",
    contentNeeds: ["service estimates", "safety information", "storm damage response content", "seasonal maintenance reminders"],
    keyTerms: ["tree removal", "canopy trimming", "stump grinding", "arborist", "hazard tree", "crown reduction"],
  },
  {
    slug: "painting-contractors",
    name: "Painting Contractors",
    type: "home-service",
    painPoints: ["providing detailed color and material estimates", "showcasing before/after transformations", "managing crew scheduling across multiple job sites", "competing with DIY and budget painters"],
    workflows: ["creating painting estimates with material breakdowns", "presenting color consultation ideas", "sending project progress updates", "requesting reviews after job completion"],
    customerType: "homeowners and commercial property managers",
    businessSize: "2-15 painters plus project manager",
    techLevel: "low",
    contentNeeds: ["project estimates", "color trend content", "before/after showcases", "seasonal painting tips"],
    keyTerms: ["primer", "finish coat", "color consultation", "exterior paint", "touch-up", "prep work"],
  },
  {
    slug: "pressure-washing",
    name: "Pressure Washing",
    type: "home-service",
    painPoints: ["showing the dramatic value of professional pressure washing", "generating leads for recurring maintenance services", "seasonal demand management", "explaining pricing for different surface types"],
    workflows: ["creating before/after content for marketing", "sending quotes for different services", "scheduling recurring service appointments", "marketing spring cleaning specials"],
    customerType: "homeowners and commercial properties",
    businessSize: "1-8 operators",
    techLevel: "low",
    contentNeeds: ["before/after showcase content", "service quotes", "seasonal promotions", "surface care guides"],
    keyTerms: ["PSI", "soft wash", "concrete cleaning", "deck restoration", "commercial pressure washing"],
  },
  {
    slug: "home-inspectors",
    name: "Home Inspectors",
    type: "professional",
    painPoints: ["writing detailed yet understandable inspection reports", "building relationships with real estate agents for referrals", "explaining findings to anxious home buyers", "differentiating from competitors in a referral-driven market"],
    workflows: ["writing inspection reports", "communicating findings to buyers and agents", "marketing to real estate professionals", "creating educational content about home maintenance"],
    customerType: "home buyers and real estate agents",
    businessSize: "solo or 2-5 inspectors",
    techLevel: "medium",
    contentNeeds: ["inspection report narratives", "educational home maintenance content", "referral network communications", "findings explanations"],
    keyTerms: ["deficiency", "material defect", "code compliance", "radon test", "structural integrity"],
  },
  {
    slug: "music-schools",
    name: "Music Schools",
    type: "education",
    painPoints: ["communicating student progress to parents", "managing recital and event logistics", "retaining students through skill plateaus", "competing with online music lesson platforms"],
    workflows: ["sending practice reminders and progress notes", "organizing recital communications", "promoting new class offerings", "managing schedule changes and makeups"],
    customerType: "students of all ages and parents of young musicians",
    businessSize: "2-10 instructors plus admin",
    techLevel: "medium",
    contentNeeds: ["progress reports", "recital announcements", "practice tips", "new class promotions"],
    keyTerms: ["recital", "lesson plan", "practice log", "music theory", "audition prep"],
  },
  {
    slug: "dance-studios",
    name: "Dance Studios",
    type: "education",
    painPoints: ["filling class rosters for new sessions and styles", "managing competition and recital logistics", "communicating costume and schedule details to parents", "retaining dancers across skill levels"],
    workflows: ["promoting class registrations", "sending competition and recital updates", "managing costume and fee communications", "creating content showcasing performances"],
    customerType: "dancers of all ages and parents of young dancers",
    businessSize: "3-12 instructors plus admin",
    techLevel: "medium",
    contentNeeds: ["registration promotions", "recital information", "competition updates", "showcase videos and posts"],
    keyTerms: ["recital", "competition team", "ballet", "jazz", "costume fitting", "choreography"],
  },
  {
    slug: "dry-cleaners",
    name: "Dry Cleaners",
    type: "service",
    painPoints: ["competing with at-home laundry and wash-and-fold services", "managing order status communications", "promoting specialty services like alterations and preservation", "building customer loyalty in a commodity business"],
    workflows: ["sending order ready notifications", "promoting seasonal specials", "managing loyalty program communications", "marketing specialty services"],
    customerType: "professionals and individuals needing garment care",
    businessSize: "3-10 staff",
    techLevel: "low",
    contentNeeds: ["order notifications", "seasonal promotions", "garment care tips", "specialty service descriptions"],
    keyTerms: ["alterations", "wedding gown preservation", "stain removal", "same-day service", "pickup and delivery"],
  },
  {
    slug: "print-shops",
    name: "Print Shops",
    type: "retail",
    painPoints: ["competing with online printing services on price", "managing complex custom order specifications", "communicating proof approvals efficiently", "upselling design services alongside printing"],
    workflows: ["managing proof approval processes", "creating custom order confirmations", "marketing large-format and specialty services", "communicating turnaround times"],
    customerType: "businesses and individuals needing printing services",
    businessSize: "3-15 production and design staff",
    techLevel: "medium",
    contentNeeds: ["proof approval communications", "product descriptions", "design service promotions", "order status updates"],
    keyTerms: ["CMYK", "bleed", "proof", "large format", "die cut", "binding"],
  },
  {
    slug: "pharmacies",
    name: "Pharmacies",
    type: "healthcare",
    painPoints: ["communicating medication information clearly and compliantly", "managing prescription refill reminders at scale", "competing with chain pharmacies and mail-order services", "handling insurance and prior authorization communications"],
    workflows: ["sending prescription ready notifications", "communicating drug interaction information", "managing refill reminders", "handling insurance coordination"],
    customerType: "patients filling prescriptions",
    businessSize: "5-15 pharmacists, techs, and staff",
    techLevel: "medium",
    contentNeeds: ["prescription notifications", "medication education", "health tips", "insurance coordination letters"],
    keyTerms: ["refill", "prior authorization", "formulary", "generic", "compound", "OTC"],
  },
  {
    slug: "event-planners",
    name: "Event Planners",
    type: "events",
    painPoints: ["creating detailed proposals that win competitive bids", "managing dozens of vendors and logistics simultaneously", "communicating timeline changes to all stakeholders", "building a portfolio that showcases range and creativity"],
    workflows: ["writing event proposals", "coordinating vendor communications", "creating event timelines and run-of-show documents", "following up with leads"],
    customerType: "corporations, nonprofits, and individuals hosting events",
    businessSize: "solo planners or teams of 2-8",
    techLevel: "medium",
    contentNeeds: ["event proposals", "vendor coordination emails", "timeline documents", "portfolio content"],
    keyTerms: ["RFP", "run of show", "floor plan", "AV requirements", "BEO", "vendor load-in"],
  },
  {
    slug: "nonprofit-organizations",
    name: "Nonprofit Organizations",
    type: "professional",
    painPoints: ["writing compelling grant applications and donor appeals", "communicating impact effectively with limited budgets", "managing volunteer coordination at scale", "producing annual reports and impact documentation"],
    workflows: ["writing grant proposals", "creating donor appeal letters", "sending volunteer coordination emails", "producing impact reports and newsletters"],
    customerType: "donors, grantmakers, volunteers, and beneficiaries",
    businessSize: "2-50 staff plus volunteers",
    techLevel: "medium",
    contentNeeds: ["grant proposals", "donor appeal letters", "impact reports", "volunteer communications", "newsletters"],
    keyTerms: ["grant cycle", "donor retention", "impact metrics", "501(c)(3)", "annual fund", "endowment"],
  },
];

export function getIndustryProfile(slug: string): IndustryProfile | undefined {
  return INDUSTRY_PROFILES.find((i) => i.slug === slug);
}
